pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t fawadrashid2/jenkin-devops-microservice .'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                // add test steps here
            }
        }
    }
    post {
        failure {
            echo 'Pipeline failed.'
        }
    }
}
